encoder:
  base_resolution: 16
  encoding: hashgrid
  input_dim: 3
  level_dim: 2
  log2_hashmap_size: 19
  num_levels: 16
exp:
  datadir: ./picklefiles/tomography_offset_128_0_0.pickle
  expdir: ./testLog/tomography_offset_128_0_0
  expname: tomography_offset_128_0_0
log:
  i_eval: 250
  i_save: 250
network:
  bound: 0.3
  hidden_dim: 32
  last_activation: sigmoid
  net_type: mlp
  num_layers: 4
  out_dim: 1
  skips:
  - 2
render:
  n_fine: 0
  n_samples: 197
  netchunk: 409600
  perturb: true
  raw_noise_std: 0.0
train:
  epoch: 250
  lrate: 0.001
  lrate_gamma: 0.1
  lrate_step: 1500
  n_batch: 1
  n_rays: 512
  resume: false
